/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecommerce;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ProductInfoClientTest {
    @Test void appHasAGreeting() {
        ProductInfoClient classUnderTest = new ProductInfoClient();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
